In [29]:
import requests

In [30]:
import pandas as pd

In [31]:
api_key = "0b5ffb7c-d88a-44c9-aa58-8f3df189012c"
url = "https://api.balldontlie.io/v1/players"
respuesta_jugadores = requests.get(url, headers = {"Authorization" : api_key}, params = {"cursor":0, "per_page":100})

In [32]:
respuesta_jugadores.status_code

200

In [33]:
datos_jugadores = respuesta_jugadores.json()

In [34]:
datos_jugadores.keys()

dict_keys(['data', 'meta'])

In [35]:
len(datos_jugadores["data"])

100

In [36]:
datos_jugadores["data"][0].keys()

dict_keys(['id', 'first_name', 'last_name', 'position', 'height', 'weight', 'jersey_number', 'college', 'country', 'draft_year', 'draft_round', 'draft_number', 'team'])

In [37]:
informacion_jugadores = {"Nombre": [], "Apellidos": [], "Equipo": []}
 
for i in datos_jugadores["data"]:
    informacion_jugadores["Nombre"].append(i["first_name"])
    informacion_jugadores["Apellidos"].append(i["last_name"])
    informacion_jugadores["Equipo"].append(i["team"]["full_name"])
print(informacion_jugadores)

{'Nombre': ['Alex', 'Jaylen', 'Steven', 'Bam', 'DeVaughn', 'LaMarcus', 'Rawle', 'Grayson', 'Jarrett', 'Al-Farouq', 'Justin', 'Kyle', 'Ryan', 'Ike', 'Giannis', 'Kostas', 'Carmelo', 'OG', 'Ryan', 'Trevor', 'D.J.', 'Deandre', 'Dwayne', 'Marvin', 'Ron', 'Wade', 'Lonzo', 'Mo', 'J.J.', 'Harrison', 'Will', 'Keita', 'Nicolas', 'Jerryd', 'Aron', 'Kent', 'Bradley', 'Malik', 'Michael', 'Marco', 'Jordan', "DeAndre'", 'Dragan', 'Davis', 'Patrick', 'Khem', 'Jabari', 'Bismack', 'Nemanja', 'Antonio', 'Eric', 'Trevon', 'Bogdan', 'Bojan', 'Jonah', 'Isaac', 'Devin', 'Chris', 'Avery', 'Tony', 'Mikal', 'Miles', 'Isaiah', 'Ryan', 'Malcolm', 'Dillon', 'MarShon', 'Troy', 'Bruce', 'Jaylen', 'Lorenzo', 'Sterling', 'Jalen', 'Thomas', 'Reggie', 'Trey', 'Alec', 'Deonte', 'Jimmy', 'Jose', 'Kentavious', 'Isaiah', 'Clint', 'DeMarre', 'Wendell', 'Michael', 'Jevon', 'Vince', 'Alex', 'Omri', 'Willie', 'Troy', 'Tyler', 'Tyson', 'Wilson', 'Joe', 'Marquese', 'Gary', 'Ian', 'Jordan'], 'Apellidos': ['Abrines', 'Adams', 'Adams', 'Adebayo', 'Akoon-Purcell', 'Aldridge', 'Alkins', 'Allen', 'Allen', 'Aminu', 'Anderson', 'Anderson', 'Anderson', 'Anigbogu', 'Antetokounmpo', 'Antetokounmpo', 'Anthony', 'Anunoby', 'Arcidiacono', 'Ariza', 'Augustin', 'Ayton', 'Bacon', 'Bagley III', 'Baker', 'Baldwin IV', 'Ball', 'Bamba', 'Barea', 'Barnes', 'Barton', 'Bates-Diop', 'Batum', 'Bayless', 'Baynes', 'Bazemore', 'Beal', 'Beasley', 'Beasley', 'Belinelli', 'Bell', 'Bembry', 'Bender', 'Bertans', 'Beverley', 'Birch', 'Bird', 'Biyombo', 'Bjelica', 'Blakeney', 'Bledsoe', 'Bluiett', 'Bogdanovic', 'Bogdanovic', 'Bolden', 'Bonga', 'Booker', 'Boucher', 'Bradley', 'Bradley', 'Bridges', 'Bridges', 'Briscoe', 'Broekhoff', 'Brogdon', 'Brooks', 'Brooks', 'Brown Jr.', 'Brown', 'Brown', 'Brown', 'Brown', 'Brunson', 'Bryant', 'Bullock', 'Burke', 'Burks', 'Burton', 'Butler', 'Calderon', 'Caldwell-Pope', 'Canaan', 'Capela', 'Carroll', 'Carter Jr.', 'Carter-Williams', 'Carter', 'Carter', 'Caruso', 'Casspi', 'Cauley-Stein', 'Caupain', 'Cavanaugh', 'Chandler', 'Chandler', 'Chealey', 'Chriss', 'Clark', 'Clark', 'Clarkson'], 'Equipo': ['Oklahoma City Thunder', 'Atlanta Hawks', 'Houston Rockets', 'Miami Heat', 'Denver Nuggets', 'Brooklyn Nets', 'Chicago Bulls', 'Phoenix Suns', 'Cleveland Cavaliers', 'Portland Trail Blazers', 'Indiana Pacers', 'Utah Jazz', 'New Orleans Pelicans', 'Indiana Pacers', 'Milwaukee Bucks', 'Chicago Bulls', 'Los Angeles Lakers', 'New York Knicks', 'New York Knicks', 'Los Angeles Lakers', 'Los Angeles Lakers', 'Los Angeles Lakers', 'Los Angeles Lakers', 'Washington Wizards', 'New York Knicks', 'Memphis Grizzlies', 'Cleveland Cavaliers', 'Utah Jazz', 'Dallas Mavericks', 'San Antonio Spurs', 'Toronto Raptors', 'Minnesota Timberwolves', 'LA Clippers', 'Milwaukee Bucks', 'Detroit Pistons', 'Sacramento Kings', 'LA Clippers', 'Detroit Pistons', 'Miami Heat', 'San Antonio Spurs', 'Chicago Bulls', 'Milwaukee Bucks', 'Phoenix Suns', 'Charlotte Hornets', 'Milwaukee Bucks', 'San Antonio Spurs', 'Boston Celtics', 'San Antonio Spurs', 'Golden State Warriors', 'Chicago Bulls', 'Portland Trail Blazers', 'Utah Jazz', 'LA Clippers', 'New York Knicks', 'Philadelphia 76ers', 'Toronto Raptors', 'Phoenix Suns', 'Boston Celtics', 'Los Angeles Lakers', 'Indiana Pacers', 'New York Knicks', 'Charlotte Hornets', 'Orlando Magic', 'Dallas Mavericks', 'New York Knicks', 'Phoenix Suns', 'Brooklyn Nets', 'Detroit Pistons', 'Denver Nuggets', 'Boston Celtics', 'Toronto Raptors', 'Los Angeles Lakers', 'New York Knicks', 'Cleveland Cavaliers', 'Houston Rockets', 'Dallas Mavericks', 'Miami Heat', 'Oklahoma City Thunder', 'Golden State Warriors', 'Toronto Raptors', 'Memphis Grizzlies', 'Philadelphia 76ers', 'Houston Rockets', 'Atlanta Hawks', 'Orlando Magic', 'Orlando Magic', 'Chicago Bulls', 'Toronto Raptors', 'Oklahoma City Thunder', 'Sacramento Kings', 'Philadelphia 76ers', 'Orlando Magic', 'Atlanta Hawks', 'New York Knicks', 'Denver Nuggets', 'Charlotte Hornets', 'Dallas Mavericks', 'New Orleans Pelicans', 'Golden State Warriors', 'New York Knicks']}

In [38]:
# informacion_jugadores[]
len(informacion_jugadores["Nombre"])

100

In [39]:
respuesta_jugadores2 = requests.get(url, headers = {"Authorization" : api_key}, params = {"cursor":100, "per_page":100})

In [40]:
datos_jugadores2 = respuesta_jugadores2.json()

In [41]:
len(datos_jugadores2["data"])

100

In [42]:
datos_jugadores2["data"]

[{'id': 101,
  'first_name': 'John',
  'last_name': 'Collins',
  'position': 'F-C',
  'height': '6-9',
  'weight': '226',
  'jersey_number': '20',
  'college': 'Wake Forest',
  'country': 'USA',
  'draft_year': 2017,
  'draft_round': 1,
  'draft_number': 19,
  'team': {'id': 13,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'LA',
   'name': 'Clippers',
   'full_name': 'LA Clippers',
   'abbreviation': 'LAC'}},
 {'id': 102,
  'first_name': 'Zach',
  'last_name': 'Collins',
  'position': 'F-C',
  'height': '6-9',
  'weight': '250',
  'jersey_number': '12',
  'college': 'Gonzaga',
  'country': 'USA',
  'draft_year': 2017,
  'draft_round': 1,
  'draft_number': 10,
  'team': {'id': 5,
   'conference': 'East',
   'division': 'Central',
   'city': 'Chicago',
   'name': 'Bulls',
   'full_name': 'Chicago Bulls',
   'abbreviation': 'CHI'}},
 {'id': 103,
  'first_name': 'Darren',
  'last_name': 'Collison',
  'position': 'G',
  'height': '6-0',
  'weight': '175',
  'jersey_number': '2',
  'college': 'UCLA',
  'country': 'USA',
  'draft_year': 2009,
  'draft_round': 1,
  'draft_number': 21,
  'team': {'id': 14,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Los Angeles',
   'name': 'Lakers',
   'full_name': 'Los Angeles Lakers',
   'abbreviation': 'LAL'}},
 {'id': 104,
  'first_name': 'Mike',
  'last_name': 'Conley',
  'position': 'G',
  'height': '6-1',
  'weight': '175',
  'jersey_number': '10',
  'college': 'Ohio State',
  'country': 'USA',
  'draft_year': 2007,
  'draft_round': 1,
  'draft_number': 4,
  'team': {'id': 18,
   'conference': 'West',
   'division': 'Northwest',
   'city': 'Minnesota',
   'name': 'Timberwolves',
   'full_name': 'Minnesota Timberwolves',
   'abbreviation': 'MIN'}},
 {'id': 105,
  'first_name': 'Pat',
  'last_name': 'Connaughton',
  'position': 'G',
  'height': '6-5',
  'weight': '209',
  'jersey_number': '21',
  'college': 'Notre Dame',
  'country': 'USA',
  'draft_year': 2015,
  'draft_round': 2,
  'draft_number': 41,
  'team': {'id': 4,
   'conference': 'East',
   'division': 'Southeast',
   'city': 'Charlotte',
   'name': 'Hornets',
   'full_name': 'Charlotte Hornets',
   'abbreviation': 'CHA'}},
 {'id': 106,
  'first_name': 'Quinn',
  'last_name': 'Cook',
  'position': 'G',
  'height': '6-1',
  'weight': '180',
  'jersey_number': '28',
  'college': 'Duke',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 26,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Sacramento',
   'name': 'Kings',
   'full_name': 'Sacramento Kings',
   'abbreviation': 'SAC'}},
 {'id': 107,
  'first_name': 'DeMarcus',
  'last_name': 'Cousins',
  'position': 'C',
  'height': '6-10',
  'weight': '270',
  'jersey_number': '4',
  'college': 'Kentucky',
  'country': 'USA',
  'draft_year': 2010,
  'draft_round': 1,
  'draft_number': 5,
  'team': {'id': 8,
   'conference': 'West',
   'division': 'Northwest',
   'city': 'Denver',
   'name': 'Nuggets',
   'full_name': 'Denver Nuggets',
   'abbreviation': 'DEN'}},
 {'id': 108,
  'first_name': 'Robert',
  'last_name': 'Covington',
  'position': 'F',
  'height': '6-7',
  'weight': '209',
  'jersey_number': '33',
  'college': 'Tennessee State',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 23,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'Philadelphia',
   'name': '76ers',
   'full_name': 'Philadelphia 76ers',
   'abbreviation': 'PHI'}},
 {'id': 109,
  'first_name': 'Allen',
  'last_name': 'Crabbe',
  'position': 'G-F',
  'height': '6-6',
  'weight': '212',
  'jersey_number': '33',
  'college': 'California',
  'country': 'USA',
  'draft_year': 2013,
  'draft_round': 2,
  'draft_number': 31,
  'team': {'id': 25,
   'conference': 'West',
   'division': 'Northwest',
   'city': 'Portland',
   'name': 'Trail Blazers',
   'full_name': 'Portland Trail Blazers',
   'abbreviation': 'POR'}},
 {'id': 110,
  'first_name': 'Torrey',
  'last_name': 'Craig',
  'position': 'F',
  'height': '6-5',
  'weight': '221',
  'jersey_number': '12',
  'college': 'South Carolina Upstate',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 2,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'Boston',
   'name': 'Celtics',
   'full_name': 'Boston Celtics',
   'abbreviation': 'BOS'}},
 {'id': 111,
  'first_name': 'Jamal',
  'last_name': 'Crawford',
  'position': 'G',
  'height': '6-5',
  'weight': '200',
  'jersey_number': '1',
  'college': 'Michigan',
  'country': 'USA',
  'draft_year': 2000,
  'draft_round': 1,
  'draft_number': 8,
  'team': {'id': 13,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'LA',
   'name': 'Clippers',
   'full_name': 'LA Clippers',
   'abbreviation': 'LAC'}},
 {'id': 112,
  'first_name': 'Jae',
  'last_name': 'Crowder',
  'position': 'F',
  'height': '6-6',
  'weight': '235',
  'jersey_number': '99',
  'college': 'Marquette',
  'country': 'USA',
  'draft_year': 2012,
  'draft_round': 2,
  'draft_number': 34,
  'team': {'id': 26,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Sacramento',
   'name': 'Kings',
   'full_name': 'Sacramento Kings',
   'abbreviation': 'SAC'}},
 {'id': 113,
  'first_name': 'Dante',
  'last_name': 'Cunningham',
  'position': 'F',
  'height': '6-8',
  'weight': '230',
  'jersey_number': '33',
  'college': 'Villanova',
  'country': 'USA',
  'draft_year': 2009,
  'draft_round': 2,
  'draft_number': 33,
  'team': {'id': 19,
   'conference': 'West',
   'division': 'Southwest',
   'city': 'New Orleans',
   'name': 'Pelicans',
   'full_name': 'New Orleans Pelicans',
   'abbreviation': 'NOP'}},
 {'id': 114,
  'first_name': 'Seth',
  'last_name': 'Curry',
  'position': 'G',
  'height': '6-1',
  'weight': '185',
  'jersey_number': '31',
  'college': 'Duke',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 10,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Golden State',
   'name': 'Warriors',
   'full_name': 'Golden State Warriors',
   'abbreviation': 'GSW'}},
 {'id': 115,
  'first_name': 'Stephen',
  'last_name': 'Curry',
  'position': 'G',
  'height': '6-2',
  'weight': '185',
  'jersey_number': '30',
  'college': 'Davidson',
  'country': 'USA',
  'draft_year': 2009,
  'draft_round': 1,
  'draft_number': 7,
  'team': {'id': 10,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Golden State',
   'name': 'Warriors',
   'full_name': 'Golden State Warriors',
   'abbreviation': 'GSW'}},
 {'id': 116,
  'first_name': 'Troy',
  'last_name': 'Daniels',
  'position': 'G',
  'height': '6-4',
  'weight': '200',
  'jersey_number': '30',
  'college': 'Va Commonwealth',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 24,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Phoenix',
   'name': 'Suns',
   'full_name': 'Phoenix Suns',
   'abbreviation': 'PHX'}},
 {'id': 117,
  'first_name': 'Anthony',
  'last_name': 'Davis',
  'position': 'F-C',
  'height': '6-10',
  'weight': '253',
  'jersey_number': '3',
  'college': 'Kentucky',
  'country': 'USA',
  'draft_year': 2012,
  'draft_round': 1,
  'draft_number': 1,
  'team': {'id': 7,
   'conference': 'West',
   'division': 'Southwest',
   'city': 'Dallas',
   'name': 'Mavericks',
   'full_name': 'Dallas Mavericks',
   'abbreviation': 'DAL'}},
 {'id': 118,
  'first_name': 'Ed',
  'last_name': 'Davis',
  'position': 'C',
  'height': '6-9',
  'weight': '218',
  'jersey_number': '21',
  'college': 'North Carolina',
  'country': 'USA',
  'draft_year': 2010,
  'draft_round': 1,
  'draft_number': 13,
  'team': {'id': 6,
   'conference': 'East',
   'division': 'Central',
   'city': 'Cleveland',
   'name': 'Cavaliers',
   'full_name': 'Cleveland Cavaliers',
   'abbreviation': 'CLE'}},
 {'id': 119,
  'first_name': 'Tyler',
  'last_name': 'Davis',
  'position': 'C',
  'height': '6-10',
  'weight': '266',
  'jersey_number': '34',
  'college': 'Texas A&M',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 21,
   'conference': 'West',
   'division': 'Northwest',
   'city': 'Oklahoma City',
   'name': 'Thunder',
   'full_name': 'Oklahoma City Thunder',
   'abbreviation': 'OKC'}},
 {'id': 120,
  'first_name': 'Dewayne',
  'last_name': 'Dedmon',
  'position': 'C',
  'height': '6-10',
  'weight': '245',
  'jersey_number': '14',
  'college': 'USC',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 23,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'Philadelphia',
   'name': '76ers',
   'full_name': 'Philadelphia 76ers',
   'abbreviation': 'PHI'}},
 {'id': 121,
  'first_name': 'Sam',
  'last_name': 'Dekker',
  'position': 'F',
  'height': '6-9',
  'weight': '230',
  'jersey_number': '8',
  'college': 'Wisconsin',
  'country': 'USA',
  'draft_year': 2015,
  'draft_round': 1,
  'draft_number': 18,
  'team': {'id': 28,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'Toronto',
   'name': 'Raptors',
   'full_name': 'Toronto Raptors',
   'abbreviation': 'TOR'}},
 {'id': 122,
  'first_name': 'Angel',
  'last_name': 'Delgado',
  'position': 'C',
  'height': '6-10',
  'weight': '245',
  'jersey_number': '31',
  'college': 'Seton Hall',
  'country': 'Dominican Republic',
  'draft_year': 2018,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 13,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'LA',
   'name': 'Clippers',
   'full_name': 'LA Clippers',
   'abbreviation': 'LAC'}},
 {'id': 123,
  'first_name': 'Matthew',
  'last_name': 'Dellavedova',
  'position': 'G',
  'height': '6-3',
  'weight': '200',
  'jersey_number': '8',
  'college': "Saint Mary's",
  'country': 'Australia',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 26,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Sacramento',
   'name': 'Kings',
   'full_name': 'Sacramento Kings',
   'abbreviation': 'SAC'}},
 {'id': 124,
  'first_name': 'Luol',
  'last_name': 'Deng',
  'position': 'F',
  'height': '6-9',
  'weight': '237',
  'jersey_number': '9',
  'college': 'Duke',
  'country': 'United Kingdom',
  'draft_year': 2004,
  'draft_round': 1,
  'draft_number': 7,
  'team': {'id': 5,
   'conference': 'East',
   'division': 'Central',
   'city': 'Chicago',
   'name': 'Bulls',
   'full_name': 'Chicago Bulls',
   'abbreviation': 'CHI'}},
 {'id': 125,
  'first_name': 'DeMar',
  'last_name': 'DeRozan',
  'position': 'G',
  'height': '6-6',
  'weight': '220',
  'jersey_number': '10',
  'college': 'Southern California',
  'country': 'USA',
  'draft_year': 2009,
  'draft_round': 1,
  'draft_number': 9,
  'team': {'id': 26,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Sacramento',
   'name': 'Kings',
   'full_name': 'Sacramento Kings',
   'abbreviation': 'SAC'}},
 {'id': 126,
  'first_name': 'Marcus',
  'last_name': 'Derrickson',
  'position': 'F',
  'height': '6-7',
  'weight': '249',
  'jersey_number': '32',
  'college': 'Georgetown',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 10,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Golden State',
   'name': 'Warriors',
   'full_name': 'Golden State Warriors',
   'abbreviation': 'GSW'}},
 {'id': 127,
  'first_name': 'Cheick',
  'last_name': 'Diallo',
  'position': 'F',
  'height': '6-8',
  'weight': '219',
  'jersey_number': '14',
  'college': 'Kansas',
  'country': 'Mali',
  'draft_year': 2016,
  'draft_round': 2,
  'draft_number': 33,
  'team': {'id': 16,
   'conference': 'East',
   'division': 'Southeast',
   'city': 'Miami',
   'name': 'Heat',
   'full_name': 'Miami Heat',
   'abbreviation': 'MIA'}},
 {'id': 128,
  'first_name': 'Hamidou',
  'last_name': 'Diallo',
  'position': 'G',
  'height': '6-5',
  'weight': '202',
  'jersey_number': '6',
  'college': 'Kentucky',
  'country': 'USA',
  'draft_year': 2018,
  'draft_round': 2,
  'draft_number': 45,
  'team': {'id': 30,
   'conference': 'East',
   'division': 'Southeast',
   'city': 'Washington',
   'name': 'Wizards',
   'full_name': 'Washington Wizards',
   'abbreviation': 'WAS'}},
 {'id': 129,
  'first_name': 'Gorgui',
  'last_name': 'Dieng',
  'position': 'C',
  'height': '6-10',
  'weight': '248',
  'jersey_number': '41',
  'college': 'Louisville',
  'country': 'Senegal',
  'draft_year': 2013,
  'draft_round': 1,
  'draft_number': 21,
  'team': {'id': 27,
   'conference': 'West',
   'division': 'Southwest',
   'city': 'San Antonio',
   'name': 'Spurs',
   'full_name': 'San Antonio Spurs',
   'abbreviation': 'SAS'}},
 {'id': 130,
  'first_name': 'Spencer',
  'last_name': 'Dinwiddie',
  'position': 'G',
  'height': '6-5',
  'weight': '215',
  'jersey_number': '26',
  'college': 'Colorado',
  'country': 'USA',
  'draft_year': 2014,
  'draft_round': 2,
  'draft_number': 38,
  'team': {'id': 4,
   'conference': 'East',
   'division': 'Southeast',
   'city': 'Charlotte',
   'name': 'Hornets',
   'full_name': 'Charlotte Hornets',
   'abbreviation': 'CHA'}},
 {'id': 131,
  'first_name': 'Donte',
  'last_name': 'DiVincenzo',
  'position': 'G',
  'height': '6-4',
  'weight': '203',
  'jersey_number': '0',
  'college': 'Villanova',
  'country': 'USA',
  'draft_year': 2018,
  'draft_round': 1,
  'draft_number': 17,
  'team': {'id': 18,
   'conference': 'West',
   'division': 'Northwest',
   'city': 'Minnesota',
   'name': 'Timberwolves',
   'full_name': 'Minnesota Timberwolves',
   'abbreviation': 'MIN'}},
 {'id': 132,
  'first_name': 'Luka',
  'last_name': 'Doncic',
  'position': 'F-G',
  'height': '6-8',
  'weight': '230',
  'jersey_number': '77',
  'college': 'Real Madrid',
  'country': 'Slovenia',
  'draft_year': 2018,
  'draft_round': 1,
  'draft_number': 3,
  'team': {'id': 14,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Los Angeles',
   'name': 'Lakers',
   'full_name': 'Los Angeles Lakers',
   'abbreviation': 'LAL'}},
 {'id': 133,
  'first_name': 'Tyler',
  'last_name': 'Dorsey',
  'position': 'G',
  'height': '6-5',
  'weight': '183',
  'jersey_number': '22',
  'college': 'Oregon',
  'country': 'USA',
  'draft_year': 2017,
  'draft_round': 2,
  'draft_number': 41,
  'team': {'id': 7,
   'conference': 'West',
   'division': 'Southwest',
   'city': 'Dallas',
   'name': 'Mavericks',
   'full_name': 'Dallas Mavericks',
   'abbreviation': 'DAL'}},
 {'id': 134,
  'first_name': 'Damyean',
  'last_name': 'Dotson',
  'position': 'G',
  'height': '6-5',
  'weight': '210',
  'jersey_number': '21',
  'college': 'Houston',
  'country': 'USA',
  'draft_year': 2017,
  'draft_round': 2,
  'draft_number': 44,
  'team': {'id': 20,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'New York',
   'name': 'Knicks',
   'full_name': 'New York Knicks',
   'abbreviation': 'NYK'}},
 {'id': 135,
  'first_name': 'PJ',
  'last_name': 'Dozier',
  'position': 'G-F',
  'height': '6-6',
  'weight': '205',
  'jersey_number': '35',
  'college': 'South Carolina',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 18,
   'conference': 'West',
   'division': 'Northwest',
   'city': 'Minnesota',
   'name': 'Timberwolves',
   'full_name': 'Minnesota Timberwolves',
   'abbreviation': 'MIN'}},
 {'id': 136,
  'first_name': 'Goran',
  'last_name': 'Dragic',
  'position': 'G',
  'height': '6-4',
  'weight': '190',
  'jersey_number': '31',
  'college': 'Union Olimpija',
  'country': 'Slovenia',
  'draft_year': 2008,
  'draft_round': 2,
  'draft_number': 45,
  'team': {'id': 17,
   'conference': 'East',
   'division': 'Central',
   'city': 'Milwaukee',
   'name': 'Bucks',
   'full_name': 'Milwaukee Bucks',
   'abbreviation': 'MIL'}},
 {'id': 137,
  'first_name': 'Andre',
  'last_name': 'Drummond',
  'position': 'C',
  'height': '6-11',
  'weight': '279',
  'jersey_number': '1',
  'college': 'Connecticut',
  'country': 'USA',
  'draft_year': 2012,
  'draft_round': 1,
  'draft_number': 9,
  'team': {'id': 23,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'Philadelphia',
   'name': '76ers',
   'full_name': 'Philadelphia 76ers',
   'abbreviation': 'PHI'}},
 {'id': 138,
  'first_name': 'Jared',
  'last_name': 'Dudley',
  'position': 'F',
  'height': '6-6',
  'weight': '237',
  'jersey_number': '10',
  'college': 'Boston College',
  'country': 'USA',
  'draft_year': 2007,
  'draft_round': 1,
  'draft_number': 22,
  'team': {'id': 24,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Phoenix',
   'name': 'Suns',
   'full_name': 'Phoenix Suns',
   'abbreviation': 'PHX'}},
 {'id': 139,
  'first_name': 'Kris',
  'last_name': 'Dunn',
  'position': 'G',
  'height': '6-3',
  'weight': '205',
  'jersey_number': '8',
  'college': 'Providence',
  'country': 'USA',
  'draft_year': 2016,
  'draft_round': 1,
  'draft_number': 5,
  'team': {'id': 13,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'LA',
   'name': 'Clippers',
   'full_name': 'LA Clippers',
   'abbreviation': 'LAC'}},
 {'id': 140,
  'first_name': 'Kevin',
  'last_name': 'Durant',
  'position': 'F',
  'height': '6-11',
  'weight': '240',
  'jersey_number': '7',
  'college': 'Texas',
  'country': 'USA',
  'draft_year': 2007,
  'draft_round': 1,
  'draft_number': 2,
  'team': {'id': 11,
   'conference': 'West',
   'division': 'Southwest',
   'city': 'Houston',
   'name': 'Rockets',
   'full_name': 'Houston Rockets',
   'abbreviation': 'HOU'}},
 {'id': 141,
  'first_name': 'Trevon',
  'last_name': 'Duval',
  'position': 'G',
  'height': '6-2',
  'weight': '189',
  'jersey_number': '0',
  'college': 'Duke',
  'country': 'USA',
  'draft_year': None,
  'draft_round': None,
  'draft_number': None,
  'team': {'id': 17,
   'conference': 'East',
   'division': 'Central',
   'city': 'Milwaukee',
   'name': 'Bucks',
   'full_name': 'Milwaukee Bucks',
   'abbreviation': 'MIL'}},
 {'id': 142,
  'first_name': 'Vincent',
  'last_name': 'Edwards',
  'position': 'F',
  'height': '6-8',
  'weight': '225',
  'jersey_number': '12',
  'college': 'Purdue',
  'country': 'USA',
  'draft_year': 2018,
  'draft_round': 2,
  'draft_number': 52,
  'team': {'id': 11,
   'conference': 'West',
   'division': 'Southwest',
   'city': 'Houston',
   'name': 'Rockets',
   'full_name': 'Houston Rockets',
   'abbreviation': 'HOU'}},
 {'id': 143,
  'first_name': 'Henry',
  'last_name': 'Ellenson',
  'position': 'F',
  'height': '6-11',
  'weight': '245',
  'jersey_number': '13',
  'college': 'Marquette',
  'country': 'USA',
  'draft_year': 2016,
  'draft_round': 1,
  'draft_number': 18,
  'team': {'id': 9,
   'conference': 'East',
   'division': 'Central',
   'city': 'Detroit',
   'name': 'Pistons',
   'full_name': 'Detroit Pistons',
   'abbreviation': 'DET'}},
 {'id': 144,
  'first_name': 'Wayne',
  'last_name': 'Ellington',
  'position': 'G',
  'height': '6-4',
  'weight': '207',
  'jersey_number': '2',
  'college': 'North Carolina',
  'country': 'USA',
  'draft_year': 2009,
  'draft_round': 1,
  'draft_number': 28,
  'team': {'id': 14,
   'conference': 'West',
   'division': 'Pacific',
   'city': 'Los Angeles',
   'name': 'Lakers',
   'full_name': 'Los Angeles Lakers',
   'abbreviation': 'LAL'}},
 {'id': 145,
  'first_name': 'Joel',
  'last_name': 'Embiid',
  'position': 'F-C',
  'height': '7-0',
  'weight': '280',
  'jersey_number': '21',
  'college': 'Kansas',
  'country': 'Cameroon',
  'draft_year': 2014,
  'draft_round': 1,
  'draft_number': 3,
  'team': {'id': 23,
   'conference': 'East',
   'division': 'Atlantic',
   'city': 'Philadelphia',
   'name': '76ers',
   'full_name': 'Philadelphia 76ers',
   'abbreviation': 'PHI'}},
 {'id': 146,
  'first_name': 'James',
  'last_name': 'Ennis III',
  'position': 'F',
  'height': '6-6',
  'weight': '215',

In [43]:
informacion_jugadores2 = {"Nombre": [], "Apellidos": [], "Equipo": []}
 
for i in datos_jugadores2["data"]:
    informacion_jugadores2["Nombre"].append(i["first_name"])
    informacion_jugadores2["Apellidos"].append(i["last_name"])
    informacion_jugadores2["Equipo"].append(i["team"]["full_name"])
print(informacion_jugadores2)

{'Nombre': ['John', 'Zach', 'Darren', 'Mike', 'Pat', 'Quinn', 'DeMarcus', 'Robert', 'Allen', 'Torrey', 'Jamal', 'Jae', 'Dante', 'Seth', 'Stephen', 'Troy', 'Anthony', 'Ed', 'Tyler', 'Dewayne', 'Sam', 'Angel', 'Matthew', 'Luol', 'DeMar', 'Marcus', 'Cheick', 'Hamidou', 'Gorgui', 'Spencer', 'Donte', 'Luka', 'Tyler', 'Damyean', 'PJ', 'Goran', 'Andre', 'Jared', 'Kris', 'Kevin', 'Trevon', 'Vincent', 'Henry', 'Wayne', 'Joel', 'James', 'Drew', 'Jacob', 'Keenan', 'Tyreke', 'Dante', 'Kenneth', 'Derrick', 'Cristiano', 'Raymond', 'Terrance', 'Yogi', 'Dorian', 'Bryn', 'Evan', "De'Aaron", 'Melvin', 'Tim', 'Channing', 'Markelle', 'Wenyen', 'Danilo', 'Langston', 'Marc', 'Pau', 'Rudy', 'Paul', 'Taj', 'Harry', 'Shai', 'Rudy', 'Aaron', 'Eric', 'Marcin', "Devonte'", 'Treveon', 'Jerami', 'Jerian', 'Danny', 'Draymond', 'Gerald', 'JaMychal', 'Jeff', 'Blake', 'Daniel', 'Tim', 'James', 'Maurice', 'Montrezl', 'Devin', 'Gary', 'Joe', 'Andrew', 'Shaquille', 'Tobias'], 'Apellidos': ['Collins', 'Collins', 'Collison', 'Conley', 'Connaughton', 'Cook', 'Cousins', 'Covington', 'Crabbe', 'Craig', 'Crawford', 'Crowder', 'Cunningham', 'Curry', 'Curry', 'Daniels', 'Davis', 'Davis', 'Davis', 'Dedmon', 'Dekker', 'Delgado', 'Dellavedova', 'Deng', 'DeRozan', 'Derrickson', 'Diallo', 'Diallo', 'Dieng', 'Dinwiddie', 'DiVincenzo', 'Doncic', 'Dorsey', 'Dotson', 'Dozier', 'Dragic', 'Drummond', 'Dudley', 'Dunn', 'Durant', 'Duval', 'Edwards', 'Ellenson', 'Ellington', 'Embiid', 'Ennis III', 'Eubanks', 'Evans', 'Evans', 'Evans', 'Exum', 'Faried', 'Favors', 'Felicio', 'Felton', 'Ferguson', 'Ferrell', 'Finney-Smith', 'Forbes', 'Fournier', 'Fox', 'Frazier Jr.', 'Frazier', 'Frye', 'Fultz', 'Gabriel', 'Gallinari', 'Galloway', 'Gasol', 'Gasol', 'Gay', 'George', 'Gibson', 'Giles III', 'Gilgeous-Alexander', 'Gobert', 'Gordon', 'Gordon', 'Gortat', 'Graham', 'Graham', 'Grant', 'Grant', 'Green', 'Green', 'Green', 'Green', 'Green', 'Griffin', 'Hamilton', 'Hardaway Jr.', 'Harden', 'Harkless', 'Harrell', 'Harris', 'Harris', 'Harris', 'Harrison', 'Harrison', 'Harris'], 'Equipo': ['LA Clippers', 'Chicago Bulls', 'Los Angeles Lakers', 'Minnesota Timberwolves', 'Charlotte Hornets', 'Sacramento Kings', 'Denver Nuggets', 'Philadelphia 76ers', 'Portland Trail Blazers', 'Boston Celtics', 'LA Clippers', 'Sacramento Kings', 'New Orleans Pelicans', 'Golden State Warriors', 'Golden State Warriors', 'Phoenix Suns', 'Dallas Mavericks', 'Cleveland Cavaliers', 'Oklahoma City Thunder', 'Philadelphia 76ers', 'Toronto Raptors', 'LA Clippers', 'Sacramento Kings', 'Chicago Bulls', 'Sacramento Kings', 'Golden State Warriors', 'Miami Heat', 'Washington Wizards', 'San Antonio Spurs', 'Charlotte Hornets', 'Minnesota Timberwolves', 'Los Angeles Lakers', 'Dallas Mavericks', 'New York Knicks', 'Minnesota Timberwolves', 'Milwaukee Bucks', 'Philadelphia 76ers', 'Phoenix Suns', 'LA Clippers', 'Houston Rockets', 'Milwaukee Bucks', 'Houston Rockets', 'Detroit Pistons', 'Los Angeles Lakers', 'Philadelphia 76ers', 'Denver Nuggets', 'Sacramento Kings', 'Golden State Warriors', 'Detroit Pistons', 'Sacramento Kings', 'Dallas Mavericks', 'Denver Nuggets', 'Houston Rockets', 'Chicago Bulls', 'Charlotte Hornets', 'Oklahoma City Thunder', 'Sacramento Kings', 'Houston Rockets', 'Minnesota Timberwolves', 'Detroit Pistons', 'San Antonio Spurs', 'Oklahoma City Thunder', 'Cleveland Cavaliers', 'Phoenix Suns', 'Sacramento Kings', 'Boston Celtics', 'Milwaukee Bucks', 'Indiana Pacers', 'Memphis Grizzlies', 'Los Angeles Lakers', 'Golden State Warriors', 'Philadelphia 76ers', 'Charlotte Hornets', 'Sacramento Kings', 'Oklahoma City Thunder', 'Minnesota Timberwolves', 'Denver Nuggets', 'Philadelphia 76ers', 'Washington Wizards', 'Portland Trail Blazers', 'Charlotte Hornets', 'Portland Trail Blazers', 'Chicago Bulls', 'Philadelphia 76ers', 'Golden State Warriors', 'Boston Celtics', 'Golden State Warriors', 'Houston Rockets', 'Boston Celtics', 'Atlanta Hawks', 'Denver Nuggets', 'LA Clippers', 'Sacramento Kings', 'Philadelphia 76ers', 'Dallas Mavericks', 'Milwaukee Bucks', 'Detroit Pistons', 'Memphis Grizzlies', 'Memphis Grizzlies', 'Detroit Pistons']}

In [44]:
informacion_jugadores

{'Nombre': ['Alex',
  'Jaylen',
  'Steven',
  'Bam',
  'DeVaughn',
  'LaMarcus',
  'Rawle',
  'Grayson',
  'Jarrett',
  'Al-Farouq',
  'Justin',
  'Kyle',
  'Ryan',
  'Ike',
  'Giannis',
  'Kostas',
  'Carmelo',
  'OG',
  'Ryan',
  'Trevor',
  'D.J.',
  'Deandre',
  'Dwayne',
  'Marvin',
  'Ron',
  'Wade',
  'Lonzo',
  'Mo',
  'J.J.',
  'Harrison',
  'Will',
  'Keita',
  'Nicolas',
  'Jerryd',
  'Aron',
  'Kent',
  'Bradley',
  'Malik',
  'Michael',
  'Marco',
  'Jordan',
  "DeAndre'",
  'Dragan',
  'Davis',
  'Patrick',
  'Khem',
  'Jabari',
  'Bismack',
  'Nemanja',
  'Antonio',
  'Eric',
  'Trevon',
  'Bogdan',
  'Bojan',
  'Jonah',
  'Isaac',
  'Devin',
  'Chris',
  'Avery',
  'Tony',
  'Mikal',
  'Miles',
  'Isaiah',
  'Ryan',
  'Malcolm',
  'Dillon',
  'MarShon',
  'Troy',
  'Bruce',
  'Jaylen',
  'Lorenzo',
  'Sterling',
  'Jalen',
  'Thomas',
  'Reggie',
  'Trey',
  'Alec',
  'Deonte',
  'Jimmy',
  'Jose',
  'Kentavious',
  'Isaiah',
  'Clint',
  'DeMarre',
  'Wendell',
  'Michael',
  'Jevon',
  'Vince',
  'Alex',
  'Omri',
  'Willie',
  'Troy',
  'Tyler',
  'Tyson',
  'Wilson',
  'Joe',
  'Marquese',
  'Gary',
  'Ian',
  'Jordan'],
 'Apellidos': ['Abrines',
  'Adams',
  'Adams',
  'Adebayo',
  'Akoon-Purcell',
  'Aldridge',
  'Alkins',
  'Allen',
  'Allen',
  'Aminu',
  'Anderson',
  'Anderson',
  'Anderson',
  'Anigbogu',
  'Antetokounmpo',
  'Antetokounmpo',
  'Anthony',
  'Anunoby',
  'Arcidiacono',
  'Ariza',
  'Augustin',
  'Ayton',
  'Bacon',
  'Bagley III',
  'Baker',
  'Baldwin IV',
  'Ball',
  'Bamba',
  'Barea',
  'Barnes',
  'Barton',
  'Bates-Diop',
  'Batum',
  'Bayless',
  'Baynes',
  'Bazemore',
  'Beal',
  'Beasley',
  'Beasley',
  'Belinelli',
  'Bell',
  'Bembry',
  'Bender',
  'Bertans',
  'Beverley',
  'Birch',
  'Bird',
  'Biyombo',
  'Bjelica',
  'Blakeney',
  'Bledsoe',
  'Bluiett',
  'Bogdanovic',
  'Bogdanovic',
  'Bolden',
  'Bonga',
  'Booker',
  'Boucher',
  'Bradley',
  'Bradley',
  'Bridges',
  'Bridges',
  'Briscoe',
  'Broekhoff',
  'Brogdon',
  'Brooks',
  'Brooks',
  'Brown Jr.',
  'Brown',
  'Brown',
  'Brown',
  'Brown',
  'Brunson',
  'Bryant',
  'Bullock',
  'Burke',
  'Burks',
  'Burton',
  'Butler',
  'Calderon',
  'Caldwell-Pope',
  'Canaan',
  'Capela',
  'Carroll',
  'Carter Jr.',
  'Carter-Williams',
  'Carter',
  'Carter',
  'Caruso',
  'Casspi',
  'Cauley-Stein',
  'Caupain',
  'Cavanaugh',
  'Chandler',
  'Chandler',
  'Chealey',
  'Chriss',
  'Clark',
  'Clark',
  'Clarkson'],
 'Equipo': ['Oklahoma City Thunder',
  'Atlanta Hawks',
  'Houston Rockets',
  'Miami Heat',
  'Denver Nuggets',
  'Brooklyn Nets',
  'Chicago Bulls',
  'Phoenix Suns',
  'Cleveland Cavaliers',
  'Portland Trail Blazers',
  'Indiana Pacers',
  'Utah Jazz',
  'New Orleans Pelicans',
  'Indiana Pacers',
  'Milwaukee Bucks',
  'Chicago Bulls',
  'Los Angeles Lakers',
  'New York Knicks',
  'New York Knicks',
  'Los Angeles Lakers',
  'Los Angeles Lakers',
  'Los Angeles Lakers',
  'Los Angeles Lakers',
  'Washington Wizards',
  'New York Knicks',
  'Memphis Grizzlies',
  'Cleveland Cavaliers',
  'Utah Jazz',
  'Dallas Mavericks',
  'San Antonio Spurs',
  'Toronto Raptors',
  'Minnesota Timberwolves',
  'LA Clippers',
  'Milwaukee Bucks',
  'Detroit Pistons',
  'Sacramento Kings',
  'LA Clippers',
  'Detroit Pistons',
  'Miami Heat',
  'San Antonio Spurs',
  'Chicago Bulls',
  'Milwaukee Bucks',
  'Phoenix Suns',
  'Charlotte Hornets',
  'Milwaukee Bucks',
  'San Antonio Spurs',
  'Boston Celtics',
  'San Antonio Spurs',
  'Golden State Warriors',
  'Chicago Bulls',
  'Portland Trail Blazers',
  'Utah Jazz',
  'LA Clippers',
  'New York Knicks',
  'Philadelphia 76ers',
  'Toronto Raptors',
  'Phoenix Suns',
  'Boston Celtics',
  'Los Angeles Lakers',
  'Indiana Pacers',
  'New York Knicks',
  'Charlotte Hornets',
  'Orlando Magic',
  'Dallas Mavericks',
  'New York Knicks',
  'Phoenix Suns',
  'Brooklyn Nets',
  'Detroit Pistons',
  'Denver Nuggets',
  'Boston Celtics',
  'Toronto Raptors',
  'Los Angeles Lakers',
  'New York Knicks',
  'Cleveland Cavaliers',
  'Houston Rockets',
  'Dallas Mavericks',
  'Miami Heat',
  'Oklahoma City Thunder',
  'Golden State Warriors',
  'Toronto Raptors',
  'Memphis Grizzlies',
  'Philadelphia 76ers',
  'Houston Rockets',
  'Atlanta Hawks',
  'Orlando Magic',
  'Orlando Magic',
  'Chicago Bulls',
  'Toronto Raptors',
  'Oklahoma City Thunder',
  'Sacramento Kings',
  'Philadelphia 76ers',
  'Orlando Magic',
  'Atlanta Hawks',
  'New York Knicks',
  'Denver Nuggets',
  'Charlotte Hornets',
  'Dallas Mavericks',
  'New Orleans Pelicans',
  'Golden State Warriors',
  'New York Knicks']}

In [45]:
informacion_jugadores2

{'Nombre': ['John',
  'Zach',
  'Darren',
  'Mike',
  'Pat',
  'Quinn',
  'DeMarcus',
  'Robert',
  'Allen',
  'Torrey',
  'Jamal',
  'Jae',
  'Dante',
  'Seth',
  'Stephen',
  'Troy',
  'Anthony',
  'Ed',
  'Tyler',
  'Dewayne',
  'Sam',
  'Angel',
  'Matthew',
  'Luol',
  'DeMar',
  'Marcus',
  'Cheick',
  'Hamidou',
  'Gorgui',
  'Spencer',
  'Donte',
  'Luka',
  'Tyler',
  'Damyean',
  'PJ',
  'Goran',
  'Andre',
  'Jared',
  'Kris',
  'Kevin',
  'Trevon',
  'Vincent',
  'Henry',
  'Wayne',
  'Joel',
  'James',
  'Drew',
  'Jacob',
  'Keenan',
  'Tyreke',
  'Dante',
  'Kenneth',
  'Derrick',
  'Cristiano',
  'Raymond',
  'Terrance',
  'Yogi',
  'Dorian',
  'Bryn',
  'Evan',
  "De'Aaron",
  'Melvin',
  'Tim',
  'Channing',
  'Markelle',
  'Wenyen',
  'Danilo',
  'Langston',
  'Marc',
  'Pau',
  'Rudy',
  'Paul',
  'Taj',
  'Harry',
  'Shai',
  'Rudy',
  'Aaron',
  'Eric',
  'Marcin',
  "Devonte'",
  'Treveon',
  'Jerami',
  'Jerian',
  'Danny',
  'Draymond',
  'Gerald',
  'JaMychal',
  'Jeff',
  'Blake',
  'Daniel',
  'Tim',
  'James',
  'Maurice',
  'Montrezl',
  'Devin',
  'Gary',
  'Joe',
  'Andrew',
  'Shaquille',
  'Tobias'],
 'Apellidos': ['Collins',
  'Collins',
  'Collison',
  'Conley',
  'Connaughton',
  'Cook',
  'Cousins',
  'Covington',
  'Crabbe',
  'Craig',
  'Crawford',
  'Crowder',
  'Cunningham',
  'Curry',
  'Curry',
  'Daniels',
  'Davis',
  'Davis',
  'Davis',
  'Dedmon',
  'Dekker',
  'Delgado',
  'Dellavedova',
  'Deng',
  'DeRozan',
  'Derrickson',
  'Diallo',
  'Diallo',
  'Dieng',
  'Dinwiddie',
  'DiVincenzo',
  'Doncic',
  'Dorsey',
  'Dotson',
  'Dozier',
  'Dragic',
  'Drummond',
  'Dudley',
  'Dunn',
  'Durant',
  'Duval',
  'Edwards',
  'Ellenson',
  'Ellington',
  'Embiid',
  'Ennis III',
  'Eubanks',
  'Evans',
  'Evans',
  'Evans',
  'Exum',
  'Faried',
  'Favors',
  'Felicio',
  'Felton',
  'Ferguson',
  'Ferrell',
  'Finney-Smith',
  'Forbes',
  'Fournier',
  'Fox',
  'Frazier Jr.',
  'Frazier',
  'Frye',
  'Fultz',
  'Gabriel',
  'Gallinari',
  'Galloway',
  'Gasol',
  'Gasol',
  'Gay',
  'George',
  'Gibson',
  'Giles III',
  'Gilgeous-Alexander',
  'Gobert',
  'Gordon',
  'Gordon',
  'Gortat',
  'Graham',
  'Graham',
  'Grant',
  'Grant',
  'Green',
  'Green',
  'Green',
  'Green',
  'Green',
  'Griffin',
  'Hamilton',
  'Hardaway Jr.',
  'Harden',
  'Harkless',
  'Harrell',
  'Harris',
  'Harris',
  'Harris',
  'Harrison',
  'Harrison',
  'Harris'],
 'Equipo': ['LA Clippers',
  'Chicago Bulls',
  'Los Angeles Lakers',
  'Minnesota Timberwolves',
  'Charlotte Hornets',
  'Sacramento Kings',
  'Denver Nuggets',
  'Philadelphia 76ers',
  'Portland Trail Blazers',
  'Boston Celtics',
  'LA Clippers',
  'Sacramento Kings',
  'New Orleans Pelicans',
  'Golden State Warriors',
  'Golden State Warriors',
  'Phoenix Suns',
  'Dallas Mavericks',
  'Cleveland Cavaliers',
  'Oklahoma City Thunder',
  'Philadelphia 76ers',
  'Toronto Raptors',
  'LA Clippers',
  'Sacramento Kings',
  'Chicago Bulls',
  'Sacramento Kings',
  'Golden State Warriors',
  'Miami Heat',
  'Washington Wizards',
  'San Antonio Spurs',
  'Charlotte Hornets',
  'Minnesota Timberwolves',
  'Los Angeles Lakers',
  'Dallas Mavericks',
  'New York Knicks',
  'Minnesota Timberwolves',
  'Milwaukee Bucks',
  'Philadelphia 76ers',
  'Phoenix Suns',
  'LA Clippers',
  'Houston Rockets',
  'Milwaukee Bucks',
  'Houston Rockets',
  'Detroit Pistons',
  'Los Angeles Lakers',
  'Philadelphia 76ers',
  'Denver Nuggets',
  'Sacramento Kings',
  'Golden State Warriors',
  'Detroit Pistons',
  'Sacramento Kings',
  'Dallas Mavericks',
  'Denver Nuggets',
  'Houston Rockets',
  'Chicago Bulls',
  'Charlotte Hornets',
  'Oklahoma City Thunder',
  'Sacramento Kings',
  'Houston Rockets',
  'Minnesota Timberwolves',
  'Detroit Pistons',
  'San Antonio Spurs',
  'Oklahoma City Thunder',
  'Cleveland Cavaliers',
  'Phoenix Suns',
  'Sacramento Kings',
  'Boston Celtics',
  'Milwaukee Bucks',
  'Indiana Pacers',
  'Memphis Grizzlies',
  'Los Angeles Lakers',
  'Golden State Warriors',
  'Philadelphia 76ers',
  'Charlotte Hornets',
  'Sacramento Kings',
  'Oklahoma City Thunder',
  'Minnesota Timberwolves',
  'Denver Nuggets',
  'Philadelphia 76ers',
  'Washington Wizards',
  'Portland Trail Blazers',
  'Charlotte Hornets',
  'Portland Trail Blazers',
  'Chicago Bulls',
  'Philadelphia 76ers',
  'Golden State Warriors',
  'Boston Celtics',
  'Golden State Warriors',
  'Houston Rockets',
  'Boston Celtics',
  'Atlanta Hawks',
  'Denver Nuggets',
  'LA Clippers',
  'Sacramento Kings',
  'Philadelphia 76ers',
  'Dallas Mavericks',
  'Milwaukee Bucks',
  'Detroit Pistons',
  'Memphis Grizzlies',
  'Memphis Grizzlies',
  'Detroit Pistons']}

In [55]:
informacion_jugadores_total = {**informacion_jugadores, **informacion_jugadores2}

In [56]:
informacion_jugadores

{'Nombre': ['Alex',
  'Jaylen',
  'Steven',
  'Bam',
  'DeVaughn',
  'LaMarcus',
  'Rawle',
  'Grayson',
  'Jarrett',
  'Al-Farouq',
  'Justin',
  'Kyle',
  'Ryan',
  'Ike',
  'Giannis',
  'Kostas',
  'Carmelo',
  'OG',
  'Ryan',
  'Trevor',
  'D.J.',
  'Deandre',
  'Dwayne',
  'Marvin',
  'Ron',
  'Wade',
  'Lonzo',
  'Mo',
  'J.J.',
  'Harrison',
  'Will',
  'Keita',
  'Nicolas',
  'Jerryd',
  'Aron',
  'Kent',
  'Bradley',
  'Malik',
  'Michael',
  'Marco',
  'Jordan',
  "DeAndre'",
  'Dragan',
  'Davis',
  'Patrick',
  'Khem',
  'Jabari',
  'Bismack',
  'Nemanja',
  'Antonio',
  'Eric',
  'Trevon',
  'Bogdan',
  'Bojan',
  'Jonah',
  'Isaac',
  'Devin',
  'Chris',
  'Avery',
  'Tony',
  'Mikal',
  'Miles',
  'Isaiah',
  'Ryan',
  'Malcolm',
  'Dillon',
  'MarShon',
  'Troy',
  'Bruce',
  'Jaylen',
  'Lorenzo',
  'Sterling',
  'Jalen',
  'Thomas',
  'Reggie',
  'Trey',
  'Alec',
  'Deonte',
  'Jimmy',
  'Jose',
  'Kentavious',
  'Isaiah',
  'Clint',
  'DeMarre',
  'Wendell',
  'Michael',
  'Jevon',
  'Vince',
  'Alex',
  'Omri',
  'Willie',
  'Troy',
  'Tyler',
  'Tyson',
  'Wilson',
  'Joe',
  'Marquese',
  'Gary',
  'Ian',
  'Jordan'],
 'Apellidos': ['Abrines',
  'Adams',
  'Adams',
  'Adebayo',
  'Akoon-Purcell',
  'Aldridge',
  'Alkins',
  'Allen',
  'Allen',
  'Aminu',
  'Anderson',
  'Anderson',
  'Anderson',
  'Anigbogu',
  'Antetokounmpo',
  'Antetokounmpo',
  'Anthony',
  'Anunoby',
  'Arcidiacono',
  'Ariza',
  'Augustin',
  'Ayton',
  'Bacon',
  'Bagley III',
  'Baker',
  'Baldwin IV',
  'Ball',
  'Bamba',
  'Barea',
  'Barnes',
  'Barton',
  'Bates-Diop',
  'Batum',
  'Bayless',
  'Baynes',
  'Bazemore',
  'Beal',
  'Beasley',
  'Beasley',
  'Belinelli',
  'Bell',
  'Bembry',
  'Bender',
  'Bertans',
  'Beverley',
  'Birch',
  'Bird',
  'Biyombo',
  'Bjelica',
  'Blakeney',
  'Bledsoe',
  'Bluiett',
  'Bogdanovic',
  'Bogdanovic',
  'Bolden',
  'Bonga',
  'Booker',
  'Boucher',
  'Bradley',
  'Bradley',
  'Bridges',
  'Bridges',
  'Briscoe',
  'Broekhoff',
  'Brogdon',
  'Brooks',
  'Brooks',
  'Brown Jr.',
  'Brown',
  'Brown',
  'Brown',
  'Brown',
  'Brunson',
  'Bryant',
  'Bullock',
  'Burke',
  'Burks',
  'Burton',
  'Butler',
  'Calderon',
  'Caldwell-Pope',
  'Canaan',
  'Capela',
  'Carroll',
  'Carter Jr.',
  'Carter-Williams',
  'Carter',
  'Carter',
  'Caruso',
  'Casspi',
  'Cauley-Stein',
  'Caupain',
  'Cavanaugh',
  'Chandler',
  'Chandler',
  'Chealey',
  'Chriss',
  'Clark',
  'Clark',
  'Clarkson'],
 'Equipo': ['Oklahoma City Thunder',
  'Atlanta Hawks',
  'Houston Rockets',
  'Miami Heat',
  'Denver Nuggets',
  'Brooklyn Nets',
  'Chicago Bulls',
  'Phoenix Suns',
  'Cleveland Cavaliers',
  'Portland Trail Blazers',
  'Indiana Pacers',
  'Utah Jazz',
  'New Orleans Pelicans',
  'Indiana Pacers',
  'Milwaukee Bucks',
  'Chicago Bulls',
  'Los Angeles Lakers',
  'New York Knicks',
  'New York Knicks',
  'Los Angeles Lakers',
  'Los Angeles Lakers',
  'Los Angeles Lakers',
  'Los Angeles Lakers',
  'Washington Wizards',
  'New York Knicks',
  'Memphis Grizzlies',
  'Cleveland Cavaliers',
  'Utah Jazz',
  'Dallas Mavericks',
  'San Antonio Spurs',
  'Toronto Raptors',
  'Minnesota Timberwolves',
  'LA Clippers',
  'Milwaukee Bucks',
  'Detroit Pistons',
  'Sacramento Kings',
  'LA Clippers',
  'Detroit Pistons',
  'Miami Heat',
  'San Antonio Spurs',
  'Chicago Bulls',
  'Milwaukee Bucks',
  'Phoenix Suns',
  'Charlotte Hornets',
  'Milwaukee Bucks',
  'San Antonio Spurs',
  'Boston Celtics',
  'San Antonio Spurs',
  'Golden State Warriors',
  'Chicago Bulls',
  'Portland Trail Blazers',
  'Utah Jazz',
  'LA Clippers',
  'New York Knicks',
  'Philadelphia 76ers',
  'Toronto Raptors',
  'Phoenix Suns',
  'Boston Celtics',
  'Los Angeles Lakers',
  'Indiana Pacers',
  'New York Knicks',
  'Charlotte Hornets',
  'Orlando Magic',
  'Dallas Mavericks',
  'New York Knicks',
  'Phoenix Suns',
  'Brooklyn Nets',
  'Detroit Pistons',
  'Denver Nuggets',
  'Boston Celtics',
  'Toronto Raptors',
  'Los Angeles Lakers',
  'New York Knicks',
  'Cleveland Cavaliers',
  'Houston Rockets',
  'Dallas Mavericks',
  'Miami Heat',
  'Oklahoma City Thunder',
  'Golden State Warriors',
  'Toronto Raptors',
  'Memphis Grizzlies',
  'Philadelphia 76ers',
  'Houston Rockets',
  'Atlanta Hawks',
  'Orlando Magic',
  'Orlando Magic',
  'Chicago Bulls',
  'Toronto Raptors',
  'Oklahoma City Thunder',
  'Sacramento Kings',
  'Philadelphia 76ers',
  'Orlando Magic',
  'Atlanta Hawks',
  'New York Knicks',
  'Denver Nuggets',
  'Charlotte Hornets',
  'Dallas Mavericks',
  'New Orleans Pelicans',
  'Golden State Warriors',
  'New York Knicks']}

In [57]:
len(informacion_jugadores["Nombre"])

100

In [58]:
informacion_jugadores_total

{'Nombre': ['John',
  'Zach',
  'Darren',
  'Mike',
  'Pat',
  'Quinn',
  'DeMarcus',
  'Robert',
  'Allen',
  'Torrey',
  'Jamal',
  'Jae',
  'Dante',
  'Seth',
  'Stephen',
  'Troy',
  'Anthony',
  'Ed',
  'Tyler',
  'Dewayne',
  'Sam',
  'Angel',
  'Matthew',
  'Luol',
  'DeMar',
  'Marcus',
  'Cheick',
  'Hamidou',
  'Gorgui',
  'Spencer',
  'Donte',
  'Luka',
  'Tyler',
  'Damyean',
  'PJ',
  'Goran',
  'Andre',
  'Jared',
  'Kris',
  'Kevin',
  'Trevon',
  'Vincent',
  'Henry',
  'Wayne',
  'Joel',
  'James',
  'Drew',
  'Jacob',
  'Keenan',
  'Tyreke',
  'Dante',
  'Kenneth',
  'Derrick',
  'Cristiano',
  'Raymond',
  'Terrance',
  'Yogi',
  'Dorian',
  'Bryn',
  'Evan',
  "De'Aaron",
  'Melvin',
  'Tim',
  'Channing',
  'Markelle',
  'Wenyen',
  'Danilo',
  'Langston',
  'Marc',
  'Pau',
  'Rudy',
  'Paul',
  'Taj',
  'Harry',
  'Shai',
  'Rudy',
  'Aaron',
  'Eric',
  'Marcin',
  "Devonte'",
  'Treveon',
  'Jerami',
  'Jerian',
  'Danny',
  'Draymond',
  'Gerald',
  'JaMychal',
  'Jeff',
  'Blake',
  'Daniel',
  'Tim',
  'James',
  'Maurice',
  'Montrezl',
  'Devin',
  'Gary',
  'Joe',
  'Andrew',
  'Shaquille',
  'Tobias'],
 'Apellidos': ['Collins',
  'Collins',
  'Collison',
  'Conley',
  'Connaughton',
  'Cook',
  'Cousins',
  'Covington',
  'Crabbe',
  'Craig',
  'Crawford',
  'Crowder',
  'Cunningham',
  'Curry',
  'Curry',
  'Daniels',
  'Davis',
  'Davis',
  'Davis',
  'Dedmon',
  'Dekker',
  'Delgado',
  'Dellavedova',
  'Deng',
  'DeRozan',
  'Derrickson',
  'Diallo',
  'Diallo',
  'Dieng',
  'Dinwiddie',
  'DiVincenzo',
  'Doncic',
  'Dorsey',
  'Dotson',
  'Dozier',
  'Dragic',
  'Drummond',
  'Dudley',
  'Dunn',
  'Durant',
  'Duval',
  'Edwards',
  'Ellenson',
  'Ellington',
  'Embiid',
  'Ennis III',
  'Eubanks',
  'Evans',
  'Evans',
  'Evans',
  'Exum',
  'Faried',
  'Favors',
  'Felicio',
  'Felton',
  'Ferguson',
  'Ferrell',
  'Finney-Smith',
  'Forbes',
  'Fournier',
  'Fox',
  'Frazier Jr.',
  'Frazier',
  'Frye',
  'Fultz',
  'Gabriel',
  'Gallinari',
  'Galloway',
  'Gasol',
  'Gasol',
  'Gay',
  'George',
  'Gibson',
  'Giles III',
  'Gilgeous-Alexander',
  'Gobert',
  'Gordon',
  'Gordon',
  'Gortat',
  'Graham',
  'Graham',
  'Grant',
  'Grant',
  'Green',
  'Green',
  'Green',
  'Green',
  'Green',
  'Griffin',
  'Hamilton',
  'Hardaway Jr.',
  'Harden',
  'Harkless',
  'Harrell',
  'Harris',
  'Harris',
  'Harris',
  'Harrison',
  'Harrison',
  'Harris'],
 'Equipo': ['LA Clippers',
  'Chicago Bulls',
  'Los Angeles Lakers',
  'Minnesota Timberwolves',
  'Charlotte Hornets',
  'Sacramento Kings',
  'Denver Nuggets',
  'Philadelphia 76ers',
  'Portland Trail Blazers',
  'Boston Celtics',
  'LA Clippers',
  'Sacramento Kings',
  'New Orleans Pelicans',
  'Golden State Warriors',
  'Golden State Warriors',
  'Phoenix Suns',
  'Dallas Mavericks',
  'Cleveland Cavaliers',
  'Oklahoma City Thunder',
  'Philadelphia 76ers',
  'Toronto Raptors',
  'LA Clippers',
  'Sacramento Kings',
  'Chicago Bulls',
  'Sacramento Kings',
  'Golden State Warriors',
  'Miami Heat',
  'Washington Wizards',
  'San Antonio Spurs',
  'Charlotte Hornets',
  'Minnesota Timberwolves',
  'Los Angeles Lakers',
  'Dallas Mavericks',
  'New York Knicks',
  'Minnesota Timberwolves',
  'Milwaukee Bucks',
  'Philadelphia 76ers',
  'Phoenix Suns',
  'LA Clippers',
  'Houston Rockets',
  'Milwaukee Bucks',
  'Houston Rockets',
  'Detroit Pistons',
  'Los Angeles Lakers',
  'Philadelphia 76ers',
  'Denver Nuggets',
  'Sacramento Kings',
  'Golden State Warriors',
  'Detroit Pistons',
  'Sacramento Kings',
  'Dallas Mavericks',
  'Denver Nuggets',
  'Houston Rockets',
  'Chicago Bulls',
  'Charlotte Hornets',
  'Oklahoma City Thunder',
  'Sacramento Kings',
  'Houston Rockets',
  'Minnesota Timberwolves',
  'Detroit Pistons',
  'San Antonio Spurs',
  'Oklahoma City Thunder',
  'Cleveland Cavaliers',
  'Phoenix Suns',
  'Sacramento Kings',
  'Boston Celtics',
  'Milwaukee Bucks',
  'Indiana Pacers',
  'Memphis Grizzlies',
  'Los Angeles Lakers',
  'Golden State Warriors',
  'Philadelphia 76ers',
  'Charlotte Hornets',
  'Sacramento Kings',
  'Oklahoma City Thunder',
  'Minnesota Timberwolves',
  'Denver Nuggets',
  'Philadelphia 76ers',
  'Washington Wizards',
  'Portland Trail Blazers',
  'Charlotte Hornets',
  'Portland Trail Blazers',
  'Chicago Bulls',
  'Philadelphia 76ers',
  'Golden State Warriors',
  'Boston Celtics',
  'Golden State Warriors',
  'Houston Rockets',
  'Boston Celtics',
  'Atlanta Hawks',
  'Denver Nuggets',
  'LA Clippers',
  'Sacramento Kings',
  'Philadelphia 76ers',
  'Dallas Mavericks',
  'Milwaukee Bucks',
  'Detroit Pistons',
  'Memphis Grizzlies',
  'Memphis Grizzlies',
  'Detroit Pistons']}

In [50]:
len(informacion_jugadores_total["Nombre"])

100

In [51]:
informacion_jugadores_total.keys()

dict_keys(['Nombre', 'Apellidos', 'Equipo'])

In [52]:
df = pd.DataFrame(informacion_jugadores)

In [53]:
df

      Nombre      Apellidos                 Equipo
0       Alex        Abrines  Oklahoma City Thunder
1     Jaylen          Adams          Atlanta Hawks
2     Steven          Adams        Houston Rockets
3        Bam        Adebayo             Miami Heat
4   DeVaughn  Akoon-Purcell         Denver Nuggets
..       ...            ...                    ...
95       Joe        Chealey      Charlotte Hornets
96  Marquese         Chriss       Dallas Mavericks
97      Gary          Clark   New Orleans Pelicans
98       Ian          Clark  Golden State Warriors
99    Jordan       Clarkson        New York Knicks

[100 rows x 3 columns]

In [59]:
df2 = pd.DataFrame(informacion_jugadores2)

In [60]:
df2

       Nombre    Apellidos                  Equipo
0        John      Collins             LA Clippers
1        Zach      Collins           Chicago Bulls
2      Darren     Collison      Los Angeles Lakers
3        Mike       Conley  Minnesota Timberwolves
4         Pat  Connaughton       Charlotte Hornets
..        ...          ...                     ...
95       Gary       Harris         Milwaukee Bucks
96        Joe       Harris         Detroit Pistons
97     Andrew     Harrison       Memphis Grizzlies
98  Shaquille     Harrison       Memphis Grizzlies
99     Tobias       Harris         Detroit Pistons

[100 rows x 3 columns]