In [59]:
import pandas as pd

In [60]:
import lxml

In [61]:
df_books = pd.read_xml("books.xml")

In [62]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            12 non-null     object
 1   author        12 non-null     object
 2   title         12 non-null     object
 3   genre         12 non-null     object
 4   price         12 non-null     float64
 5   publish_date  12 non-null     object
 6   description   12 non-null     object
dtypes: float64(1), object(6)
memory usage: 804.0+ bytes

In [63]:
df_books.head(2)

,id,author,title,genre,price,publish_date,description
0,bk101,"Gambardella, Matthew",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications \n ...
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."

In [64]:
df_books.columns

Index(['id', 'author', 'title', 'genre', 'price', 'publish_date',
       'description'],
      dtype='object')

In [65]:
df_books.tail(2)

,id,author,title,genre,price,publish_date,description
10,bk111,"O'Brien, Tim",MSXML3: A Comprehensive Guide,Computer,36.95,2000-12-01,The Microsoft MSXML3 parser is covered in \n ...
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

In [66]:
df_books.sample(3)

,id,author,title,genre,price,publish_date,description
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."
7,bk108,"Knorr, Stefan",Creepy Crawlies,Horror,4.95,2000-12-06,"An anthology of horror stories about roaches,\..."
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

In [67]:
df_books.isnull()

       id  author  title  genre  price  publish_date  description
0   False   False  False  False  False         False        False
1   False   False  False  False  False         False        False
2   False   False  False  False  False         False        False
3   False   False  False  False  False         False        False
4   False   False  False  False  False         False        False
5   False   False  False  False  False         False        False
6   False   False  False  False  False         False        False
7   False   False  False  False  False         False        False
8   False   False  False  False  False         False        False
9   False   False  False  False  False         False        False
10  False   False  False  False  False         False        False
11  False   False  False  False  False         False        False

In [68]:
df_books.isnull().sum()

id              0
author          0
title           0
genre           0
price           0
publish_date    0
description     0
dtype: int64

In [69]:
df_movies = pd.read_csv("christmas_movies.csv", index_col = False)

In [70]:
df_movies.head()

,title,rating,runtime,imdb_rating,meta_score,genre,release_year,description,director,stars,votes,gross,img_src,type
0,Love Actually,R,135.0,7.6,55.0,"Comedy, Drama, Romance",2003.0,Follows the lives of eight very different coup...,Richard Curtis,"Hugh Grant, Martine McCutcheon, Liam Neeson, L...","517,283",$59.70M,https://m.media-amazon.com/images/M/MV5BNThkNj...,Movie
1,Home Alone,PG,103.0,7.7,63.0,"Comedy, Family",1990.0,"An eight-year-old troublemaker, mistakenly lef...",Chris Columbus,"Macaulay Culkin, Joe Pesci, Daniel Stern, John...","629,713",$285.76M,https://m.media-amazon.com/images/M/MV5BMzFkM2...,Movie
2,National Lampoon's Christmas Vacation,PG-13,97.0,7.5,49.0,Comedy,1989.0,The Griswold family's plans for a big family C...,Jeremiah S. Chechik,"Chevy Chase, Beverly D'Angelo, Juliette Lewis,...","213,196",$71.32M,https://m.media-amazon.com/images/M/MV5BMGZkMW...,Movie
3,Elf,PG,97.0,7.1,66.0,"Adventure, Comedy, Family",2003.0,"Raised as an oversized elf, Buddy travels from...",Jon Favreau,"Will Ferrell, James Caan, Bob Newhart, Zooey D...","300,546",$173.40M,https://m.media-amazon.com/images/M/MV5BMzUxNz...,Movie
4,How the Grinch Stole Christmas,PG,104.0,6.3,46.0,"Comedy, Family, Fantasy",2000.0,"On the outskirts of Whoville lives a green, re...",Ron Howard,"Jim Carrey, Taylor Momsen, Kelley, Jeffrey Tam...","280,898",$260.04M,https://m.media-amazon.com/images/M/MV5BNWNiNT...,Movie

In [71]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 873 entries, 0 to 872
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         873 non-null    object
 1   rating        660 non-null    object
 2   runtime       832 non-null    float64
 3   imdb_rating   839 non-null    float64
 4   meta_score    100 non-null    float64
 5   genre         872 non-null    object
 6   release_year  862 non-null    float64
 7   description   873 non-null    object
 8   director      868 non-null    object
 9   stars         862 non-null    object
 10  votes         839 non-null    object
 11  gross         79 non-null     object
 12  img_src       873 non-null    object
 13  type          873 non-null    object
dtypes: float64(4), object(10)
memory usage: 95.6+ KB

In [72]:
df_movies.describe()

          runtime  imdb_rating  meta_score  release_year
count  832.000000   839.000000  100.000000    862.000000
mean    86.596154     6.100477   57.650000   2009.498840
std     18.152062     0.966392   17.901174     20.274696
min      1.000000     1.300000   18.000000   1898.000000
25%     84.000000     5.600000   46.750000   2010.000000
50%     87.000000     6.200000   56.000000   2017.000000
75%     91.000000     6.700000   69.000000   2020.000000
max    199.000000     9.200000   96.000000   2023.000000

In [73]:
df_movies.columns

Index(['title', 'rating', 'runtime', 'imdb_rating', 'meta_score', 'genre',
       'release_year', 'description', 'director', 'stars', 'votes', 'gross',
       'img_src', 'type'],
      dtype='object')

In [74]:
df_movies.tail()

,title,rating,runtime,imdb_rating,meta_score,genre,release_year,description,director,stars,votes,gross,img_src,type
868,CBS News Sunday Morning with Jane Pauley: Epis...,TV-G,NaN,NaN,NaN,"News, Talk-Show",1979.0,The popularity of pickup trucks; Luke Burbank ...,Kate D'Arcy-Coleman,"Jane Pauley, Serena Altschul, Nicholas Britell...",NaN,NaN,https://m.media-amazon.com/images/M/MV5BMWJhYz...,TV Episode
869,Honest Ads: If Holiday Movies Were Honest,NaN,NaN,NaN,NaN,"Short, Comedy",2012.0,What if Hollywood were honest about how they m...,Michael Strauss,"Jack Hunter, Britt Migs, Michael Strauss,",NaN,NaN,https://m.media-amazon.com/images/M/MV5BNzY1Nj...,TV Episode
870,Cosmic Cowboys: Céréal Christmas,NaN,NaN,NaN,NaN,Animation,2004.0,Add a Plot,NaN,NaN,NaN,NaN,https://m.media-amazon.com/images/S/sash/i-t32...,TV Episode
871,Proper Manors: Christmas Special: Christmas Pa...,NaN,20.0,NaN,NaN,"Action, Comedy, Crime",2012.0,Miles Barnes is forced to throw contractually-...,Dallin Boyce,"Brandyn Cross, Peter D'Alessio, Janis Race-Big...",NaN,NaN,https://m.media-amazon.com/images/S/sash/i-t32...,TV Episode
872,Sacred Music at Christmas: A Choral Christmas,NaN,NaN,NaN,NaN,"Documentary, Music",2010.0,Add a Plot,NaN,NaN,NaN,NaN,https://m.media-amazon.com/images/S/sash/i-t32...,TV Episode

In [75]:
df_movies.to_csv("prueba_movies.csv", index=False)

In [76]:
import json

In [77]:
with open("one_piece.json", "r") as fichero:
    fichero_one_piece = json.load(fichero)

In [78]:
fichero_one_piece

[{'rank': '24,129',
  'trend': '18',
  'season': 1,
  'episode': 1,
  'name': "I'm Luffy! The Man Who Will Become the Pirate King!",
  'start': 1999,
  'total_votes': '647',
  'average_rating': 7.6},
 {'rank': '29,290',
  'trend': '11',
  'season': 1,
  'episode': 2,
  'name': 'The Great Swordsman Appears! Pirate Hunter, Roronoa Zoro',
  'start': 1999,
  'total_votes': '473',
  'average_rating': 7.8},
 {'rank': '32,043',
  'trend': '7',
  'season': 1,
  'episode': 3,
  'name': "Morgan vs. Luffy! Who's This Beautiful Young Girl?",
  'start': 1999,
  'total_votes': '428',
  'average_rating': 7.7},
 {'rank': '28,818',
  'trend': '8',
  'season': 1,
  'episode': 4,
  'name': "Luffy's Past! The Red-haired Shanks Appears!",
  'start': 1999,
  'total_votes': '449',
  'average_rating': 8.1},
 {'rank': '37,113',
  'trend': '4',
  'season': 1,
  'episode': 5,
  'name': 'Fear, Mysterious Power! Pirate Clown Captain Buggy!',
  'start': 1999,
  'total_votes': '370',
  'average_rating': 7.5},
 {'rank': '36,209',
  'trend': '4',
  'season': 1,
  'episode': 6,
  'name': 'Desperate Situation! Beast Tamer Mohji vs. Luffy!',
  'start': 1999,
  'total_votes': '364',
  'average_rating': 7.7}]

In [79]:
import openpyxl

In [80]:
df_libros = pd.read_excel("libros_ejemplo.xlsx")

In [81]:
df_libros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 5 non-null      int64
 1   Nombre             5 non-null      object
 2   Autor              5 non-null      object
 3   Precio             5 non-null      float64
 4   Fecha_Publicacion  5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [82]:
df_libros.head(2)

   ID   Nombre    Autor  Precio Fecha_Publicacion
0   1  Libro A  Autor 1   15.99        2021-05-10
1   2  Libro B  Autor 2   23.50        2020-11-15

In [83]:
df_prueba_libros = df_libros.head(2) #Guardamos en un nuevo df las dos primeras filas del Excel original

In [84]:
df_prueba_libros #Comprobamos que efectivamente los ha guardado

   ID   Nombre    Autor  Precio Fecha_Publicacion
0   1  Libro A  Autor 1   15.99        2021-05-10
1   2  Libro B  Autor 2   23.50        2020-11-15

In [85]:
df_prueba_libros.to_excel("excel_prueba_libros.xlsx")

In [88]:

prueba_diccionario = {"nombre": "Ana", "edad": 25, "cursos": ["Python", "Data Analyst"]}

In [89]:
prueba_diccionario

{'nombre': 'Ana', 'edad': 25, 'cursos': ['Python', 'Data Analyst']}

In [90]:
prueba_diccionario.keys()

dict_keys(['nombre', 'edad', 'cursos'])

In [91]:
with open("prueba_diccionario.json", "w") as file:
    json.dump(prueba_diccionario, file)

In [93]:
df_prueba_diccionario = pd.read_json("prueba_diccionario.json")

In [94]:
df_prueba_diccionario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  2 non-null      object
 1   edad    2 non-null      int64
 2   cursos  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes